//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTSharp.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_pt_br {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_pt_br() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTSharp.Domain.Resources.Messages_pt-br", typeof(Messages_pt_br).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletado.
        /// </summary>
        internal static string Act_Deleted {
            get {
                return ResourceManager.GetString("Act_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salvo.
        /// </summary>
        internal static string Act_Save {
            get {
                return ResourceManager.GetString("Act_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizado.
        /// </summary>
        internal static string Act_Update {
            get {
                return ResourceManager.GetString("Act_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to algo deu errado.
        /// </summary>
        internal static string Ex_ExceptionGeneric {
            get {
                return ResourceManager.GetString("Ex_ExceptionGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item não encontrado com o id {0}.
        /// </summary>
        internal static string Ex_ItemNotFound {
            get {
                return ResourceManager.GetString("Ex_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        internal static string L_Email {
            get {
                return ResourceManager.GetString("L_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to senha.
        /// </summary>
        internal static string L_Password {
            get {
                return ResourceManager.GetString("L_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} e {1} devem ser iguais.
        /// </summary>
        internal static string V_AreEquals {
            get {
                return ResourceManager.GetString("V_AreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} e {1} não são iguais.
        /// </summary>
        internal static string V_AreNotEqual {
            get {
                return ResourceManager.GetString("V_AreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve estar contido em {1}.
        /// </summary>
        internal static string V_Contains {
            get {
                return ResourceManager.GetString("V_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ter o mesmo tamanho {1} de caractere(s).
        /// </summary>
        internal static string V_HasExactLengthIfNotNullOrEmpty {
            get {
                return ResourceManager.GetString("V_HasExactLengthIfNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ter o tamanho {1} de caractere(s).
        /// </summary>
        internal static string V_HasLen {
            get {
                return ResourceManager.GetString("V_HasLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ter o tamanho maior que {1} caractere(s).
        /// </summary>
        internal static string V_HasMaxLen {
            get {
                return ResourceManager.GetString("V_HasMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ter o tamanho maior que {1} caractere(s).
        /// </summary>
        internal static string V_HasMaxLengthIfNotNullOrEmpt {
            get {
                return ResourceManager.GetString("V_HasMaxLengthIfNotNullOrEmpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ter o tamanho menor que {1} caractere(s).
        /// </summary>
        internal static string V_HasMinLen {
            get {
                return ResourceManager.GetString("V_HasMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ter o tamanho menor que {1} caractere(s).
        /// </summary>
        internal static string V_HasMinLengthIfNotNullOrEmpty {
            get {
                return ResourceManager.GetString("V_HasMinLengthIfNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve estar entre {1} e {2}.
        /// </summary>
        internal static string V_IsBetween {
            get {
                return ResourceManager.GetString("V_IsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser numérico.
        /// </summary>
        internal static string V_IsDigit {
            get {
                return ResourceManager.GetString("V_IsDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail deve ser válido.
        /// </summary>
        internal static string V_IsEmail {
            get {
                return ResourceManager.GetString("V_IsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail deve ser válido ou vazio.
        /// </summary>
        internal static string V_IsEmailOrEmpty {
            get {
                return ResourceManager.GetString("V_IsEmailOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é vazio.
        /// </summary>
        internal static string V_IsEmpty {
            get {
                return ResourceManager.GetString("V_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é falso.
        /// </summary>
        internal static string V_IsFalse {
            get {
                return ResourceManager.GetString("V_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser maior ou igual a {1}.
        /// </summary>
        internal static string V_IsGreaterOrEqualsThan {
            get {
                return ResourceManager.GetString("V_IsGreaterOrEqualsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser maior que {1}.
        /// </summary>
        internal static string V_IsGreaterThan {
            get {
                return ResourceManager.GetString("V_IsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser menor ou igual a {1}.
        /// </summary>
        internal static string V_IsLowerOrEqualsThan {
            get {
                return ResourceManager.GetString("V_IsLowerOrEqualsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser menor que {1}.
        /// </summary>
        internal static string V_IsLowerThan {
            get {
                return ResourceManager.GetString("V_IsLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não deve ser um e-mail.
        /// </summary>
        internal static string V_IsNotEmail {
            get {
                return ResourceManager.GetString("V_IsNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não deve estar vazio.
        /// </summary>
        internal static string V_IsNotEmpty {
            get {
                return ResourceManager.GetString("V_IsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser maior que {1}.
        /// </summary>
        internal static string V_IsNotGreaterThan {
            get {
                return ResourceManager.GetString("V_IsNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não deve ser null.
        /// </summary>
        internal static string V_IsNotNull {
            get {
                return ResourceManager.GetString("V_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não deve ser null ou empty.
        /// </summary>
        internal static string V_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("V_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não deve ser null ou espaço em branco.
        /// </summary>
        internal static string V_IsNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("V_IsNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser null.
        /// </summary>
        internal static string V_IsNull {
            get {
                return ResourceManager.GetString("V_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser null ou vazio.
        /// </summary>
        internal static string V_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("V_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser null ou nullable.
        /// </summary>
        internal static string V_IsNullOrNullable {
            get {
                return ResourceManager.GetString("V_IsNullOrNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser true.
        /// </summary>
        internal static string V_IsTrue {
            get {
                return ResourceManager.GetString("V_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser url.
        /// </summary>
        internal static string V_IsUrl {
            get {
                return ResourceManager.GetString("V_IsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser url ou vazio.
        /// </summary>
        internal static string V_IsUrlOrEmpty {
            get {
                return ResourceManager.GetString("V_IsUrlOrEmpty", resourceCulture);
            }
        }
    }
}
